### ISSUE TITLE
Update to latest justinrainbow json schema please

### ISSUE THREAD

**Issue by mlambley** [Leko/php-json-schema-faker#3]
Good day, 
I have projects which require `justinrainbow/json-schema ^5.2`
They obviously clash with your `~2.0`
Is there any chance you can update to the latest version? Thanks.

**Comment by Leko** [comment]
Hi @mlambley.
I just update dependencies and published 1.0.
https://packagist.org/packages/leko/json-schema-faker#1.0

Thank you for reporting that.
